### ISSUE TITLE
Error Loading Eclipse Plugin

### ISSUE THREAD

**Issue by bagnos** [axmor/typecs#43]
!SESSION 2015-04-07 12:51:41.893 -----------------------------------------------

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.6.0_45
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product -vm C:\progs\
Jdk\jdk1.7.0_51\jre\bin\javaw.exe
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.
package.jee.product -vm C:\progs\Jdk\jdk1.7.0_51\jre\bin\javaw.exe -consolelog

!ENTRY com.axmor.eclipse.typescript 4 0 2015-04-07 12:51:43.374
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.axmor.eclipse.
typescript [889]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaS
E)(version=1.7))"

```
    at org.eclipse.osgi.container.Module.start(Module.java:434)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incSta
```

rtLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incSta
rtLevel(ModuleContainer.java:1561)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doCont
ainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispat
chEvent(ModuleContainer.java:1476)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispat
chEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(Even
tManager.java:340)

!ENTRY com.axmor.eclipse.typescript.builder 4 0 2015-04-07 12:51:43.382
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.axmor.eclipse.
typescript.builder [890]
  Unresolved requirement: Require-Bundle: com.axmor.eclipse.typescript.core
    -> Bundle-SymbolicName: com.axmor.eclipse.typescript.core; bundle-version="3
.1.0.201502192009"; singleton:="true"
       com.axmor.eclipse.typescript.core [891]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.e
e=JavaSE)(version=1.7))"

```
    at org.eclipse.osgi.container.Module.start(Module.java:434)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incSta
```

rtLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incSta
rtLevel(ModuleContainer.java:1561)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doCont
ainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispat
chEvent(ModuleContainer.java:1476)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispat
chEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(Even
tManager.java:340)

!ENTRY com.axmor.eclipse.typescript.core 4 0 2015-04-07 12:51:43.398
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.axmor.eclipse.
typescript.core [891]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaS

**Comment by kosz78** [comment]
It seems you use old version of Java:

> java.version=1.6.0_45

You need use 1.7 or higher
Try to specify Java version in eclipse.ini like https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Windows_Example
