### ISSUE TITLE
support TypeScript version 1.5

### ISSUE THREAD

**Issue by atsu85** [axmor/typecs#47]
Hello,
Please add the support for version 1.5 as alpha version of TypeScript 1.5  is out, as announced here: 
http://blogs.msdn.com/b/typescript/archive/2015/03/27/announcing-typescript-1-5-alpha.aspx

**Comment by atsu85** [comment]
Looks like there are no big changes in this plugin since February. Is this plugin out of active development by now? TS1.5 support is almost a "must have" for Aurelia + TypeScript setup. Looks like VS, Atom and WebStorm support TS1.5-beta already...

**Comment by kosz78** [comment]
We plan add suport of TS1.5 a soon

**Comment by kosz78** [comment]
Implemented in the latest development build

**Comment by pcafstockf** [comment]
Outstanding !  Thank You. Looking forward to trying it out.
