### ISSUE TITLE
Issue generating single js file

### ISSUE THREAD

**Issue by brunobenvenuti** [axmor/typecs#48]
I tried to generate a single .js file by setting "Target directory or file" with a valid file name, let's, say mycompiledts.js. Whenever I save one ts file, mycompiledts.js file is generated with only this ts file compiled contents. 

I would expect to have ALL ts files compiled contents (my project has many of them) concatenated in mycompiledts.js, not only the last changed ts file.

In Palantir, there is a "Compile all TypeScript files on build" option, which leads to the output I wanted.

**Comment by kosz78** [comment]
@brunobenvenuti to compile in one file You need specify main TS file as input:
![image](https://cloud.githubusercontent.com/assets/3992195/7477906/d15d697e-f378-11e4-87fb-42ac5cf7f8ca.png)

**Comment by brunobenvenuti** [comment]
Hi, Kosz. The scenario is a bit different: I have many ts files and can't select a specific one as the "source directory of file"! 
I believe it would be necessary to compile all ts files on every change... But I don't know if we would face performance issues using this approach.

**Comment by p-kudrin** [comment]
Looks like is duplicated by #14.
Fixed in #68.
