### ISSUE TITLE
Refactoring bug

### ISSUE THREAD

**Issue by wolfgang-ch** [axmor/typecs#52]
Steps to reproduce the bug
- open a .ts file
- enter a new line at the end of the line where a refactoring should be done
- select word which should be refactored, in this example the 'i'
- press Ctrl-R
- enter a new name and show preview
- the new line is not displayed in the left part of the refactor dialog

When the file is saved before refactoring then it works correctly.

![typecs-bug-1](https://cloud.githubusercontent.com/assets/1283445/7468101/9495c8c0-f304-11e4-8184-1493aa776860.png)

![typecs-bug-2](https://cloud.githubusercontent.com/assets/1283445/7468100/9490776c-f304-11e4-88f9-ba47b8ad7970.png)

**Comment by kosz78** [comment]
Fixed in PR #61
