### ISSUE TITLE
Incorrect folder generated for JS

### ISSUE THREAD

**Issue by ttony** [axmor/typecs#55]
Hi there,

i am having problem on the folder being generated on js files. Here is my initial ts files.

![Fig_1](https://cloud.githubusercontent.com/assets/744147/7648114/62d1606e-fb11-11e4-86da-73a13306c2ee.png)

Also this is my settings for output folder:

![Fig_2](https://cloud.githubusercontent.com/assets/744147/7648158/073935b4-fb12-11e4-9a72-f48fa45ad4ee.png)

I made simple change on alertService.ts and save the file, plugin generated the js files:

![Fig_3](https://cloud.githubusercontent.com/assets/744147/7648222/dde3ebe0-fb12-11e4-82a7-99bddc584d0b.png)

Problem (which are highlighted in yellow) is Alert.js and alertServices.js somehow generated under new folder called services. basically, the output should be:

ts/common/
   --models/
        Alert.js
        Alert.ts
   --services/
        alertService.js
        alertService.ts

Is this currently a bug in plugin or do i have to configure others setting?

Cheers,

-Y

**Comment by kosz78** [comment]
You set target directory to empty

**Comment by ttony** [comment]
if set target directory to empty, then the output are:

![image](https://cloud.githubusercontent.com/assets/744147/7649293/36ff9bd8-fb1e-11e4-846c-d062983b2bbb.png)

the output should be inside under ts, rather than as root folder (showed in the Figure above)

**Comment by kosz78** [comment]
OK, its clear
