### ISSUE TITLE
Color scheme for editor

### ISSUE THREAD

**Issue by fkereki** [axmor/typecs#64]
I'm using the Eclipse Color Plugin at http://eclipsecolorthemes.org/ and it seems that the TS editor doesn't respect most of the theme colors. 

To reproduce this, use the Eclipse Color Plugin and pick a really colorful theme ("Vibrant Ink" is a good option) and compare a TS editor screen with a JS editor screen -- all colors are used in the latter, but the former shows only a couple of colors. (Please, see attached image.)

I suggest that the TS editor should be able to work with standard color themes, and it should look like the JS editor, without having to redefine by hand each and every color.

![colors_bug_typecs](https://cloud.githubusercontent.com/assets/2468063/8269864/d22473e4-1794-11e5-961e-6af4241ad1a9.png)

**Comment by p-kudrin** [comment]
We added integration with this plugin in our project. But it's need additional support in the Eclipsecolorthemes plugin. We've created the pull request [#228](https://github.com/eclipse-color-theme/eclipse-color-theme/pull/228) to support  the Typesc plugin. Hope to see it in the next Eclipsecolorthemes release.

**Comment by fkereki** [comment]
Great job! Hope to see it soon, then. Many thanks!
