### ISSUE TITLE
Can't locate: "Add TypeScript Definition from Catalog"

### ISSUE THREAD

**Issue by pitosalas** [axmor/typecs#65]
This might be a silly question but I can't find that command that is mentioned on your site. I want to figure out the 'right' way to incorporate type definitions etc. Thanks for a very cool app!

**Comment by p-kudrin** [comment]
Please try to press Ctrl + Shift + D. This should work.

**Comment by pitosalas** [comment]
Hm, I tried that, and it doesn't do anything... Here's what I have installed:
![screen shot 2015-06-29 at 5 48 50 pm](https://cloud.githubusercontent.com/assets/44681/8419359/20fe1c24-1e87-11e5-9f9c-dedb60fa6033.png)

**Comment by p-kudrin** [comment]
What OS do you use? And what eclipse version?
Other way to open TypeScript Definition: Right click on opened .ts file - Source - Add TypeScript Definition from Catalog...

**Comment by pitosalas** [comment]
I must have something more serious wrong. I am on Mac OS X Yosemite. I am running Eclipse Kepler Service Release 2. And when I right click on the opened .ts file I don't see a source option. See attached images. Thanks!

![screen shot 2015-06-30 at 3 25 57 pm](https://cloud.githubusercontent.com/assets/44681/8439825/6874e44c-1f3c-11e5-820e-9884b40f3795.png)
![screen shot 2015-06-30 at 3 25 13 pm](https://cloud.githubusercontent.com/assets/44681/8439831/6d0ac17a-1f3c-11e5-9541-720a5243803a.png)

**Comment by p-kudrin** [comment]
Please try right click within opened document (not project view).

**Comment by p-kudrin** [comment]
And also can you try to press Command + Shift + D to open TypeScript Definition. I have not MacOS to test it myself.

**Comment by pitosalas** [comment]
Yes, that worked. But where’s the command supposed to be on the menu? Why is such an important command so well hidden?

Also, where are the type files stored in Eclipse, does it have it’s own copy of them?

— Pito

On June 30, 2015 at 11:54:47 PM, p-kudrin (notifications@github.com) wrote:

And also can you try to press Command + Shift + D to open TypeScript Definition. I have not MacOS to test it myself.

**Comment by p-kudrin** [comment]
What do you mean by "the type files"? I don't shure that I understand you correctly.

**Comment by pitosalas** [comment]
I mean *.d.ts files
