### ISSUE TITLE
UI freezes

### ISSUE THREAD

**Issue by renataogarcia** [axmor/typecs#72]
I'm experiencing UI freezes while using typecs. Report can be seen [here](https://gist.github.com/renataogarcia/43542a62409c98a9dd6f).

I'm using a SNAPSHOT of Typecs 4.0.0.

This happens when editing the file below taken from the TS tutorial, for instance:

``` ts
class Student {
    fullname : string;
    constructor(public firstname, public middleinitial, public lastname) {
        this.fullname = firstname + " " + middleinitial + " " + lastname;
    }
}

interface Person {
    firstname: string;
    lastname: string;
}

function greeter(person : Person) {
    return "Hello, " + person.firstname + " " + person.lastname;
}

var user = new Student("Jane", "M.", "User");
```

**Comment by renataogarcia** [comment]
I figured from the stacktrace that it is related to code format - disabling auto format on save helps, but it still hangs when trying to format code.

**Comment by renataogarcia** [comment]
Added another ui freeze report. This time during seems to be caused when automatic content assist is triggered.

**Comment by kosz78** [comment]
fixed in the latest commit
