### ISSUE TITLE
How to highlight occurences?

### ISSUE THREAD

**Issue by kaktus40** [axmor/typecs#87]
Hello,
I install typecs from site update (not from the market) in eclipse 4.5.1.   Does typecs highlights occurrences like in others eclipse plugin? I use the dark theme from the market for information. Is there any informations about this feature?

**Comment by p-kudrin** [comment]
Yes. Typecs can  highlight occurrences.  Mark Occurrences mode can be toggled from toolbar menu or by pressing Alt+Shift+O. The IDE will highlight all occurrences of the selected keyword in the active editor tab.
Do you mean the Eclipse Color Plugin at http://eclipsecolorthemes.org/ ? We added integration with this plugin in our project. But it's need additional support in the Eclipsecolorthemes plugin. We've created the pull request #228 to support the Typesc plugin. Hope to see it in the next Eclipsecolorthemes release. So currently you may have some problems with Mark Occurrences in dark theme.

**Comment by kaktus40** [comment]
For information it's the "default" dark theme (maybe coming with eclipse 4.5.1). It's ok for me, I can now highlights the occurrences. 
Thanks
